BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[HourRequest] ADD [createdAt] DATETIME2 NOT NULL CONSTRAINT [HourRequest_createdAt_df] DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE [dbo].[LeaveRequest] ADD [createdAt] DATETIME2 NOT NULL CONSTRAINT [LeaveRequest_createdAt_df] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
